# Site
# repository: 
# favicon: images/favicon.ico

# Personal info
name: 이정헌
title: Android Developer
email: dlrkdgjs82@naver.com
# website: 

# Social links
# twitter_username: 
# github_username:
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# linkedin_username: 
# pinterest_username: 
# youtube_username: 

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  5년차 안드로이드 개발자로 학부 과정 중 대학 선후배들과 **IT스타트업**을 공동 창업하여 외주 개발, 자체서비스 운영 경험이 있습니다.<br/><br/>
  <mark>주도적인 업무 환경</mark>을 선호하며 먼저 경험하고 전파하는 것을 좋아합니다.<br/>
  본능적으로 <mark>공부하는 개발자</mark>이며 새로운 도구를 겁내지 않습니다.<br/>
  <mark>확장성</mark>과 <mark>유지 보수성</mark>이 높은 설계를 지향하며 언제나 고민하고 있습니다.<br/>
  멋진 동료들과의 <mark>팀워크</mark>를 갈망하고 있습니다.<br/><br/>
  제가 쌓아온 역량과 커뮤니케이션 능력을 활용하여 회사와 함께 **성장하는 개발자**가 되겠습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
markdown: kramdown
kramdown:
  auto_ids: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

